# PS C:\Users\abdul\Desktop\python\personal_practice\ch-13Prac> virtualenv abdullah
# created virtual environment CPython3.12.3.final.0-64 in 7638ms
#   creator CPython3Windows(dest=C:\Users\abdul\Desktop\python\personal_practice\ch-13Prac\abdullah, clear=False, no_vcs_ignore=False, global=False)
#   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=C:\Users\abdul\AppData\Local\pypa\virtualenv)
#     added seed packages: pip==25.0.1
#   activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
# PS C:\Users\abdul\Desktop\python\personal_practice\ch-13Prac> pip install -r .\requirments.txt
# Requirement already satisfied: asgiref==3.8.1 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 1)) (3.8.1)
# Requirement already satisfied: beautifulsoup4==4.12.3 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 2)) (4.12.3)
# Requirement already satisfied: certifi==2024.6.2 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 3)) (2024.6.2)
# Requirement already satisfied: comtypes==1.4.9 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 4)) (1.4.9)
# Requirement already satisfied: contourpy==1.3.1 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 5)) (1.3.1)
# Requirement already satisfied: crispy-bootstrap5==2024.2 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 6)) (2024.2)
# Requirement already satisfied: cycler==0.12.1 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 7)) (0.12.1)
# Requirement already satisfied: distlib==0.3.8 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 8)) (0.3.8)
# Requirement already satisfied: Django==4.2.13 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 9)) (4.2.13)
# Requirement already satisfied: django-bootstrap-v5==1.0.11 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 10)) (1.0.11)
# Requirement already satisfied: django-crispy-forms==2.3 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 11)) (2.3)
# Requirement already satisfied: filelock==3.14.0 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 12)) (3.14.0)
# Requirement already satisfied: fonttools==4.56.0 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 13)) (4.56.0)
# Requirement already satisfied: fpdf==1.7.2 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 14)) (1.7.2)
# Requirement already satisfied: kiwisolver==1.4.8 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 15)) (1.4.8)
# Requirement already satisfied: matplotlib==3.10.1 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 16)) (3.10.1)
# Requirement already satisfied: MouseInfo==0.1.3 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 17)) (0.1.3)
# Requirement already satisfied: numpy==1.26.4 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 18)) (1.26.4)
# Requirement already satisfied: opencv-contrib-python==4.9.0.80 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 19)) (4.9.0.80)
# Requirement already satisfied: packaging==24.2 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 20)) (24.2)
# Requirement already satisfied: pandas==2.2.3 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 21)) (2.2.3)
# Requirement already satisfied: pillow==10.4.0 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 22)) (10.4.0)
# Requirement already satisfied: pipenv==2024.0.0 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 23)) (2024.0.0)
# Requirement already satisfied: platformdirs==4.2.2 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 24)) (4.2.2)
# Requirement already satisfied: psutil==7.0.0 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 25)) (7.0.0)
# Requirement already satisfied: PyAutoGUI==0.9.54 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 26)) (0.9.54)
# Requirement already satisfied: pygame==2.6.0 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 27)) (2.6.0)
# Requirement already satisfied: PyGetWindow==0.0.9 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 28)) (0.0.9)
# Requirement already satisfied: PyMsgBox==1.0.9 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 29)) (1.0.9)
# Requirement already satisfied: pyparsing==3.2.1 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 30)) (3.2.1)
# Requirement already satisfied: pyperclip==1.8.2 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 31)) (1.8.2)
# Requirement already satisfied: pypiwin32==223 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 32)) (223)
# Requirement already satisfied: PyRect==0.2.0 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 33)) (0.2.0)
# Requirement already satisfied: PyScreeze==0.1.30 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 34)) (0.1.30)
# Requirement already satisfied: python-dateutil==2.9.0.post0 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 35)) (2.9.0.post0)
# Requirement already satisfied: pyttsx3==2.98 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 36)) (2.98)
# Requirement already satisfied: pytweening==1.2.0 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 37)) (1.2.0)
# Requirement already satisfied: pytz==2025.2 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 38)) (2025.2)
# Requirement already satisfied: pywin32==308 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 39)) (308)
# Requirement already satisfied: setuptools==70.0.0 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 40)) (70.0.0)
# Requirement already satisfied: six==1.17.0 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 41)) (1.17.0)
# Requirement already satisfied: soupsieve==2.5 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 42)) (2.5)
# Requirement already satisfied: sqlparse==0.5.0 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 43)) (0.5.0)
# Requirement already satisfied: tzdata==2024.1 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 44)) (2024.1)
# Requirement already satisfied: virtualenv==20.26.2 in c:\users\abdul\appdata\local\programs\python\python312\lib\site-packages (from -r .\requirments.txt (line 45)) (20.26.2)
# PS C:\Users\abdul\Desktop\python\personal_practice\ch-13Prac>